name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Lint title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: npx --no-install commitlint <<< "$TITLE"
      - name: Build
        run: npm run build -- --force
