name: GitHub pages

on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./site
          cname: drops.warframestat.us
          force_orphan: false
          user_name: 'Jimmy Bot'
          user_email: 'translator@warframe.gg'
      - name: Pushback
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          chmod +x .github/pushback.sh
          ./.github/pushback.sh
